### PR TITLE
#516

### LINKED ISSUE #516: Prevent all the wfilter error messages in Error Log
It would be good to stop `wfilter` filling the Error Log with irrelevant errors like:

```
2017-04-23 14:09:04: ********
2017-04-23 14:09:04: 14:09:04 ERROR:   wfilter: app Brother HL-1110 series @ Iain’… is not registered!
2017-04-23 14:09:04: ********
```

### PR DESCRIPTION
**Pull request by latenitefilms**
- Prevent all the wfilter error messages in Error Log
- cp.apple.finalcutpro now uses a single instance of hs.window.filter
- Closes #516

### CODE REVIEW

**Comment by latenitefilms** [comment]
@randomeizer - Ready for review!

File: src/extensions/cp/apple/finalcutpro/init.lua [hunk 1]
```diff
@@ -1349,67 +1340,52 @@ function App:unwatch(id)
...
-					self._active = true
-					event = "active"
-				elseif self._active == true and (eventType == watcher.deactivated or eventType == watcher.terminated) then
-					self._active = false
-					event = "inactive"
+	--log.df("Setting up Application Watcher...")
+	self._appWatcher = applicationwatcher.new(
+		function(appName, eventType, application)
+			if (application:bundleID() == App.BUNDLE_ID) then
+				if eventType == applicationwatcher.activated then
```
Comment (randomeizer) [inline src/extensions/cp/apple/finalcutpro/init.lua:1366]: Quick question - you removed the check for 'isFrontmost'. Was it redundant? I have vague recollections about adding the extra check so that it would only be notifying people about being 'active' when it was the top application.

Comment (randomeizer) [reply src/extensions/cp/apple/finalcutpro/init.lua:1366]: Some testing reveals it is all good ;)

**Review by randomeizer — APPROVED** [review]
