### PR TITLE
#1476

### LINKED ISSUE #1476: Scanning Bug
```
CommandPost v1.0.0-beta.30

Date Built:                     Aug 27 2018, 23:11:17
macOS Version:                  10.13.6
CommandPost Locale:             en
Current Keyboard Layout:        U.S.
Final Cut Pro Path:             /Applications/Final Cut Pro.app
Final Cut Pro Version:          10.4.3
Final Cut Pro Language:         en
Developer Mode:                 false

2018-08-27 22:59:27: 2018-08-27 22:59:26: -- Loading /Applications/CommandPost.app/Contents/Resources/extensions/cp/init.lua
2018-08-27 22:59:26: -- Loading extension: uielement
2018-08-27 22:59:27: 22:59:27         cp:     Garbage Collector Pause: 200
2018-08-27 22:59:27:                          Garbage Collector Step Multiplier: 200
2018-08-27 22:59:27:              config:     Automatic Script Reloading Enabled
2018-08-27 22:59:27:                  cp:     Loading Plugins...
2018-08-27 22:59:29: 22:59:29                 Plugins Loaded.
2018-08-27 22:59:29: -- Done.
2018-08-27 22:59:46: 22:59:46       scan:     ---------------------------------------------------------
2018-08-27 22:59:46:                          FINAL CUT PRO PLUGIN SCANNER:
2018-08-27 22:59:46:                          ---------------------------------------------------------
2018-08-27 22:59:46:                          * Scanning app-bundled plugins:
2018-08-27 22:59:46:                            * Loaded App Plugins from Cache: 0.096678
2018-08-27 22:59:46:                              * scanAppPlugins(en) took: 0.09746
2018-08-27 22:59:46:                           
2018-08-27 22:59:46:                          * Scanning system-installed plugins:
2018-08-27 22:59:46: ********
2018-08-27 22:59:46: 22:59:46 ERROR:   LuaSkin: hs.timer callback error: ...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:549: attempt to call a nil value
stack traceback:
	...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:549: in function 'cp.apple.finalcutpro.plugins._getPluginName'
	...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:640: in method 'handlePluginDirectory'
	...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:722: in method 'scanPluginCategoryDirectory'
	...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:692: in method 'scanPluginTypeDirectory'
	...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:620: in method 'scanPluginsDirectory'
	...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:1030: in method 'scanSystemMotionTemplates'
	...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:1641: in method 'scanSystemPlugins'
	...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:1724: in function <...ts/Resources/extensions/cp/apple/finalcutpro/plugins.lua:1693>
	(...tail calls...)
	...pp/Contents/Resources/plugins/finalcutpro/setup/scan.lua:69: in function <...pp/Contents/Resources/plugins/finalcutpro/setup/scan.lua:68>
2018-08-27 22:59:46: ********
```

### PR DESCRIPTION
**Pull request by latenitefilms**
- Added better error handling for `hs.fs.dir()` processing
- Closes #1476

### CODE REVIEW

File: src/extensions/cp/tools/init.lua [hunk 1]
```diff
@@ -1180,21 +1185,29 @@ end
...
-                    ok, err = os.remove(filePath)
-                end
-                if not ok then
-                    return nil, err
+        --------------------------------------------------------------------------------
+        -- Remove the contents:
+        --------------------------------------------------------------------------------
+        local iterFn, dirObj = fs.dir(path)
+        if not iterFn then
+            log.ef("An error occured in cp.tools.rmdir: %s", dirObj)
```
Comment (randomeizer) [inline src/extensions/cp/tools/init.lua]: If we're returning the error, we probably shouldn't log it as well.

File: src/extensions/cp/tools/init.lua [hunk 2]
```diff
@@ -1149,7 +1149,7 @@ end
 ---  * path - A path as string
 ---
 --- Returns:
----  * A table containing filenames as strings.
+---  * A table containing filenames as strings, or an empty table if an error occurs.
```
Comment (randomeizer) [inline src/extensions/cp/tools/init.lua]: This should probably be " or `nil` followed by the error message if an error occurs."

**Review by randomeizer — CHANGES_REQUESTED** [review]
Generally looks good, just a couple of improvements regarding handling the errors.

**Review by randomeizer — APPROVED** [review]
Looks good.
